version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
         - apt-get update
         - apt install wget
         - apt install -y testng
         - apt-get install -y nunit-console
         - curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
         - echo "deb [arch=amd64]  http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
         - apt -y update
         - apt -y install google-chrome-stable
         - wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
         - unzip chromedriver_linux64.zip
         - mv chromedriver /usr/bin/chromedriver
         - chown root:root /usr/bin/chromedriver
         - chmod +x /usr/bin/chromedriver
         - wget https://selenium-release.storage.googleapis.com/3.13/selenium-server-standalone-3.13.0.jar
         - pwd
         - ls
         - google-chrome --version
         - chromedriver --version
         - apt-get update
         - apt-get install -y apt-transport-https
         - apt-get update
         - apt-get install -y dotnet-sdk-2.1
         - apt-get update
         - apt-get install -y apt-transport-https
         - apt-get update
         - apt-get install -y aspnetcore-runtime-2.1
         - apt update
         - apt-get install dotnet-sdk-2.0.0
         
  build:
    commands:
         - echo Build started on `date`
         - ls
         - cd Rafa.Tests
         - dotnet restore
         - dotnet test
         